import django.db.models.deletion
from django.db import migrations, models

class Migration(migrations.Migration):
    initial = True
    dependencies = []
    operations = [
        migrations.CreateModel(name="Repository", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("name", models.CharField(max_length=100)), ("owner", models.CharField(max_length=100)), ("full_name", models.CharField(max_length=201, unique=True)), ("visibility", models.CharField(default="public", max_length=20)), ("html_url", models.URLField(blank=True))]),
        migrations.CreateModel(name="Workflow", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("name", models.CharField(max_length=150)), ("file_name", models.CharField(blank=True, max_length=150)), ("is_active", models.BooleanField(default=True)), ("repository", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="workflows", to="pipelines.repository"))], options={"ordering": ["name"], "unique_together": {("repository", "name")}}),
        migrations.CreateModel(name="PipelineRun", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("run_number", models.PositiveIntegerField()), ("commit_sha", models.CharField(blank=True, max_length=40)), ("commit_message", models.CharField(blank=True, max_length=255)), ("branch", models.CharField(default="main", max_length=150)), ("status", models.CharField(choices=[("queued", "Queued"), ("running", "Running"), ("success", "Successful"), ("failure", "Failed"), ("cancelled", "Cancelled")], default="queued", max_length=12)), ("trigger", models.CharField(choices=[("push", "Push"), ("pull_request", "Pull request"), ("manual", "Manual"), ("schedule", "Schedule")], default="push", max_length=20)), ("actor", models.CharField(blank=True, max_length=100)), ("duration_seconds", models.PositiveIntegerField(default=0)), ("failure_summary", models.TextField(blank=True)), ("logs_url", models.URLField(blank=True)), ("started_at", models.DateTimeField(blank=True, null=True)), ("completed_at", models.DateTimeField(blank=True, null=True)), ("created_at", models.DateTimeField()), ("workflow", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="runs", to="pipelines.workflow"))], options={"ordering": ["-run_number"], "unique_together": {("workflow", "run_number")}}),
        migrations.CreateModel(name="PipelineStage", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("name", models.CharField(max_length=100)), ("detail", models.CharField(blank=True, max_length=180)), ("order", models.PositiveSmallIntegerField()), ("status", models.CharField(choices=[("queued", "Queued"), ("running", "Running"), ("success", "Successful"), ("failure", "Failed"), ("skipped", "Skipped"), ("cancelled", "Cancelled")], default="queued", max_length=12)), ("duration_seconds", models.PositiveIntegerField(default=0)), ("failure_message", models.TextField(blank=True)), ("logs_url", models.URLField(blank=True)), ("run", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="stages", to="pipelines.pipelinerun"))], options={"ordering": ["order"], "unique_together": {("run", "order")}}),
    ]
